
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dumps
  namespace: infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-dumps-pv
spec:
  storageClassName: ""
  capacity:
    storage: 3Gi
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  claimRef:
    name: db-dumps
    namespace: infra
  local:
    path: /tmp/db-dumps
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
