# @formatter:off


{{ if not .Values.secrets.skip }}

  {{-  $secretName := printf "%s-%s" .Release.Name "dolibarr-secrets" -}}
  {{-  $adminPassword := "" -}}

  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
  {{- if $secret }}
    {{- $adminPassword = index $secret.data "admin-password" -}}
  {{- else -}}
    {{- if .Values.secrets.generate -}}
      {{- $adminPassword = randAlphaNum 24 | b64enc }}
    {{- else -}}
      {{- $adminPassword = .Values.secrets.adminPassword | b64enc -}}
    {{- end -}}
  {{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  admin-password: {{ $adminPassword }}


{{ end }}


---
